#!/bin/sh
IFCONFIG=`which ifconfig`

if [ "$1" != "" ]; then
	myip=`ifconfig $1 | grep "inet addr" | awk {'print $2'} | sed -e s/addr\://i`
	mask=`ifconfig $1 | grep "inet addr" | awk {'print $4'} | sed -e s/mask\://i`
	echo $myip/$mask
else 
	for int in `/usr/local/bin/lsint`; do
		myip=`ifconfig $int | grep "inet addr" | awk {'print $2'} | sed -e s/addr\://i`
		mask=`ifconfig $int | grep "inet addr" | awk {'print $4'} | sed -e s/mask\://i`
	done
fi
