#!/bin/sh
#
# coProject by C.J. Steele <coreyjsteele@yahoo.com>
# 
# script aids in the checking out of code from SVN
# 

REPOS=`cfgctl svn.repospath`
PROJ=`basename \`pwd\``
SVN=`which svn`
SVNADMIN=`which svnadmin`

echo Current projects are... 
for f in `ls -1 $REPOS`; do
	echo "    * $f"
done
