#!/usr/bin/perl 
# filename: contact.cgi
# (C)opyright 1999-2000, M-tron Industries, Inc., all rights reserved.
#	written by Corey J. Steele <csteele@mtron.com>
# last modified: 12/12/2000
#
# Description: this is a simple script that processes the dead-end product 
#	request forms for the parametric search site.  Basically, the 
#	important thing to remember here (unless changing the data that
#	is gathered on that form (which is defined in search.con) is that 
#	the people who recieve this message are held in the array 
#	@contract_recipients in cfg/ParametricSearch.pl
#
print "Content-type: text/html", "\n\n";

use CGI::Carp qw( fatalsToBrowser );
use CGI;
use lib qw( lib cfg );
use ParseLib;
use NewLog;
use MIME::Lite;
require "ParametricSearch.pl";

#
# this is the file we're going to log to
$LogFile = "deadends.log";

Tokenize( 'ELAPSED_TIME', "0" );

LoadTemplate( "content/layout.tmpl", "content/contact.con" );

main {

	$name = CGI::param( "name" );
	$title = CGI::param( "title" );
	$company = CGI::param( "company" );
	$email = CGI::param( "email" );
	$telephone = CGI::param( "tele" );
	$pc = CGI::param( "contact" );
	$values = CGI::param( "values" );
	$filled = CGI::param( "filled" );

	if( $pc eq "email" and $email eq "" ){ $filled = 0; }
	elsif( $pc eq "telephone" and $telephone eq "" ){ $filled = 0; }

	if( $name eq "" or $company eq "" ){ $filled = 0; }

	Parse( "HEADER", "SECTION_HEAD" );
	if( $filled ){

		Parse( "THANKYOU" );

		$date = `date`; chomp( $date );
		MIME::Lite->send( 'smtp', 'paen.mtron.com', Timeout => 20 )
			or die "Can't setup sendmail...";

		$body = "date: $date\n-----\nCONTACT INFORMATION\nname: $name\ntitle: $title\ncompany: $company\ne-mail: $email\ntelephone: $telephone\nprefered contact method: $pc\n-----\nPRODUCT INFORMATION\n-----\n";

		$log_entry = "$name}$title}$company}$email}telephone}$pc";

		foreach $valuePair ( split(/}/, $values ) ){
			my( $key, $val ) = split( / = /, $valuePair );
			$body .= "$key: $val\n";
			$log_entry .= "}$key=$val";
		}


		#
		# here, we're just doing the logging.
		NewLog( 'inf', '07', "$log_entry" );

		$body .= "\n-----\ngenerated by Parametric Search $__Tokens{'__VERSION'}\n";

		#
		# here, we're generating the message to send to each person to recieve the e-mail... we also send it at the end.
		foreach( @main::contact_recipients ){
			$message = MIME::Lite->new(
				From => "parametric\@mtron.com",
				  To => "$_",
			     Subject => "Product Request Form - $date",
				Type => "text/plain",
			    Encoding => '7bit',
				Data => "$body" );
			$message->send;
		}

	} else {

		#
		# They didn't fill out the form properly, so they get an error and are told to go back.
		LoadTemplate( "content/error.con" );
		Parse( "ERR-300", "ERROR_FOOTER" );

	}
	Parse( "SECTION_FOOT", "FOOTER" );

	Output();
	
}

exit( 0 );
