#!/usr/bin/perl
# filename: feedback.cgi
# (C)opyright 1999-2000, M-tron Industries, Inc., all rights reserved.
# 	written by Corey J. Steele <csteele@mtron.com>
# last modified: 12/12/2000
#
# Description: This script processes user feedback forms from argo's 
#	homepage.  this is not the dead end search, but rather just the 
#	site feedback form.  It's pretty straight forward. The list of
#	people recieving the e-mail about these comments is held in
#	cfg/ParametricSearch.pl in the array @feedback_recipients
#
print "Content-type: text/html", "\n\n";

use CGI::Carp qw( fatalsToBrowser );
use CGI;
use lib qw( lib cfg );
use NewLog;
use ParseLib;
use MIME::Lite;
require "ParametricSearch.pl";

Tokenize( 'ELAPSED_TIME', "0" );

$filled = CGI::param( 'filled' );
	$filled = 0 if( $filled eq "" );
$name = CGI::param( 'name' );
$title = CGI::param( 'title' );
$company = CGI::param( 'company' );
$email = CGI::param( 'email' );
$rating = CGI::param( 'rating' );
@comments = CGI::param( 'comments' );

$s_comments .= $_ foreach( @comments );

#
# the file to dump feedback to

#
# we need the standard stuff.
LoadTemplate( "content/layout.tmpl", "content/feedback.con" );

Tokenize( 'HELP_TOPIC', "Feedback" );

Parse( "HEADER", "SECTION_HEAD" );
if( $filled ){

	#
	# the form was completed (even partially)
	Parse( "THANKYOU" );

	NewLog( 'inf', '0D', "name=$name}title=$title}company=$company}email=$email}rating=$rating}comments=$s_comments" );

	$date = `date`; chomp( $date );
	MIME::Lite->send( 'smtp', 'paen.mtron.com', Timeout => 20 )
		or die "Can't setup sendmail...";
	$body = "date: $date\n-----\nname: $name\ntitle: $title\ncompany name: $company\ne-mail: $email\nrating: $rating\ncomments: $s_comments\n-----\ngenerated by Parametric Search $__Tokens{'__VERSION'}\n";
	foreach( @main::feedback_recipients ){
		$message = MIME::Lite->new( 
			From => "parametric\@mtron.com",
			  To => "$_",
		     Subject => "Feedback Form - $date",
			Type => "text/plain",
		    Encoding => '7bit',
			Data => "$body" );
		$message->send; 
	}

} else {

	#
	# the form has not been completed
	Parse( "FEEDBACK_FORM" );

}
Parse( "SECTION_FOOT", "FOOTER" );

Output();


#
# leave cleanly
exit( 0 );
