#!/usr/bin/perl
use strict;

if( $ARGV[0] ) 
{
	foreach( @ARGV )
	{
		my( $num, $die ) = split(/d/, $_, 2 ); 
		my $total = 0;
		for( my $x = 1; $x <= $num; $x++ )
		{
			my $roll = int( rand( $die ) + 1 );
			print "d$die $x: $roll\n";
			$total += $roll;
		} #end for
		print "==========\n";
		print "  total: $total\n";
		print "  average: ", $total / $num, "\n\n";
	} #end foreach
} else {
	#no dice specified...
	print "usage: roll 3d4\n";
	exit( 1 );
}

exit( 0 );
